name: CI Pipeline UNEZPAÃ‘OL

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.14

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          pip install pylint mypy pytest pytest-cov

      - name: Ejecutar Pylint
        run: |
          pylint $(git ls-files '*.py') || true

      - name: Ejecutar Mypy
        run: |
          mypy . --ignore-missing-imports

      - name: Ejecutar pruebas + cobertura
        run: |
          pytest --cov=./ --cov-report=xml
